//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chutzpah.Facts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chutzpah.Facts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&quot;jasmine.js&quot; /&gt;
        ////// &lt;reference path=&quot;coffee.js&quot; /&gt;
        ////*globals describe, it, expect, jasmine, coffee*/
        ///
        ///(function () {
        ///    &apos;use strict&apos;;
        ///
        ///    describe(&apos;coffee&apos;, function () {
        ///        describe(&apos;machine&apos;, function () {
        ///            it(&apos;makes a single shot flat white given milk and 1 shot&apos;, function () {
        ///                waits(5000);
        ///                runs(function () {
        ///                    var actual = coffee.machine(1, &apos;milk&apos;, false),
        ///                        expected = &apos;single shot  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JasmineSuite {
            get {
                return ResourceManager.GetString("JasmineSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&quot;jasmine.js&quot; /&gt;
        ////// &lt;reference path=&quot;coffee.js&quot; /&gt;
        ////*globals describe, it, expect, jasmine, coffee*/
        ///
        ///(function () {
        ///    &apos;use strict&apos;;
        ///
        ///    describe(&apos;coffee&apos;, function () {
        ///        describe(&apos;machine&apos;, function () {
        ///            it(&apos;makes a single shot flat white given milk and 1 shot&apos;, function () {
        ///                waits(5000);
        ///                runs(function () {
        ///                    var actual = coffee.machine(1, &apos;milk&apos;, false),
        ///                        expected = &apos;single shot  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QUnitSuite {
            get {
                return ResourceManager.GetString("QUnitSuite", resourceCulture);
            }
        }
    }
}
