//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chutzpah.Facts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chutzpah.Facts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;
        ///  &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;Jasmine Spec Runner&lt;/title&gt;
        ///
        ///  &lt;link rel=&quot;shortcut icon&quot; type=&quot;image/png&quot; href=&quot;jasmine_favicon.png&quot;&gt;
        ///
        ///  &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;jasmine.css&quot;&gt;
        ///  &lt;script type=&quot;text/javascript&quot; src=&quot;jasmine.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script type=&quot;text/javascript&quot; src=&quot;jasmine-html.js&quot;&gt;&lt;/script&gt;
        ///
        ///  &lt;script type=&quot;text/javascript&quot; src=&quot;library.js&quot;&gt;&lt;/script&gt;
        ///
        ///  &lt;script type=&quot;tex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JasmineHarness {
            get {
                return ResourceManager.GetString("JasmineHarness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&quot;jasmine.js&quot; /&gt;
        ///// Example copied from https://github.com/michaelphines/Jasmine-Examples/blob/master/example-3/spec/javascript/exampleSpec.js
        ///
        ///describe(&apos;Greeter&apos;, function () {
        ///    describe(&apos;#sayHello()&apos;, function () {
        ///        var greeter;
        ///        beforeEach(function () {
        ///            greeter = new Greeter(&apos;&apos;);
        ///        });
        ///
        ///        it(&apos;says hello&apos;, function () {
        ///            expect(greeter.sayHello()).toMatch(/^Hello, .*!$/);
        ///        });
        ///
        ///        it(&apos;uses the name&apos;, function  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JasmineSuite {
            get {
                return ResourceManager.GetString("JasmineSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## &lt;reference path=&quot;jasmine.js&quot; /&gt;
        ///
        ///describe &quot;general&quot;, -&gt;
        ///  it &quot;A basic test&quot;, -&gt;
        ///    expect(true).toBeTruthy()
        ///    value = &quot;hello&quot;
        ///    expect(&quot;hello&quot;).toEqual value
        ///
        ///
        ///describe &quot;stringLib&quot;, -&gt;
        ///  it &quot;will get vowel count&quot;, -&gt;
        ///    count = stringLib.vowels(&quot;hello&quot;)
        ///    expect(count).toEqual 2
        ///
        ///
        ///describe &quot;mathLib&quot;, -&gt;
        ///  beforeEach -&gt;
        ///    console.log &quot;beforeEach&quot;
        ///
        ///  it &quot;will add 5 to number&quot;, -&gt;
        ///    res = mathLib.add5(10)
        ///    expect(res).toEqual 15
        ///
        ///  it &quot;will multiply 5 to number&quot;, -&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JasmineSuiteCoffee {
            get {
                return ResourceManager.GetString("JasmineSuiteCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&quot;jsspec.js&quot; /&gt;
        ///// Example copied from http://jania.pe.kr/jsspec/demo.html
        ///
        ///describe(&apos;Plus operator (just for example)&apos;, {
        ///    &apos;should concatenate two strings&apos;: function () {
        ///        expect(&quot;Hello &quot; + &quot;World&quot;).should_be(&quot;Hello World&quot;);
        ///    },
        ///    &apos;should add two numbers&apos;: function () {
        ///        expect(1 + 2).should_be(3);
        ///    }
        ///})
        ///
        ///describe(&apos;&quot;Should match&quot;s&apos;, {
        ///    &apos;Should match&apos;: function () {
        ///        expect(&quot;Hello&quot;).should_match(/ell/);
        ///    },
        ///    &apos;Should match 1&apos;: functi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSSpecSuite {
            get {
                return ResourceManager.GetString("JSSpecSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&quot;browser_controlled_runner.js&quot; /&gt;
        ///// Example copied from http://code.google.com/p/js-test-driver/source/browse/samples/hello-world/src-test/GreeterTest.js
        ///
        ///GreeterTest = TestCase(&quot;GreeterTest&quot;);
        ///
        ///GreeterTest.prototype.testGreet = function () {
        ///    var greeter = new myapp.Greeter();
        ///    assertEquals(&quot;Hello World!&quot;, greeter.greet(&quot;World&quot;));
        ///    jstestdriver.console.log(&quot;JsTestDriver&quot;, greeter.greet(&quot;World&quot;));
        ///    console.log(greeter.greet(&quot;Browser&quot;, &quot;World&quot;));
        ///};
        ///.
        /// </summary>
        internal static string JsTestDriverSuite {
            get {
                return ResourceManager.GetString("JsTestDriverSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;
        ///  &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;Jasmine Spec Runner&lt;/title&gt;
        ///
        ///  &lt;link rel=&quot;shortcut icon&quot; type=&quot;image/png&quot; href=&quot;jasmine_favicon.png&quot;&gt;
        ///
        ///  &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;jasmine.css&quot;&gt;
        ///  &lt;script type=&quot;text/javascript&quot; src=&quot;jasmine.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script type=&quot;text/javascript&quot; src=&quot;jasmine-html.js&quot;&gt;&lt;/script&gt;
        ///
        ///  &lt;script type=&quot;text/javascript&quot; src=&quot;library.js&quot;&gt;&lt;/script&gt;
        ///
        ///  &lt;script type=&quot;tex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MochaHarness {
            get {
                return ResourceManager.GetString("MochaHarness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&quot;mocha.js&quot; /&gt;
        ///// Example copied from https://github.com/michaelphines/Jasmine-Examples/blob/master/example-3/spec/javascript/exampleSpec.js
        ///
        ///describe(&apos;Greeter&apos;, function () {
        ///    describe(&apos;#sayHello()&apos;, function () {
        ///        var greeter;
        ///        beforeEach(function () {
        ///            greeter = new Greeter(&apos;&apos;);
        ///        });
        ///
        ///        it(&apos;says hello&apos;, function () {
        ///            expect(greeter.sayHello()).toMatch(/^Hello, .*!$/);
        ///        });
        ///
        ///        it(&apos;uses the name&apos;, function () [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MochaSuite {
            get {
                return ResourceManager.GetString("MochaSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## &lt;reference path=&quot;mocha.js&quot; /&gt;
        ///
        ///describe &quot;general&quot;, -&gt;
        ///  it &quot;A basic test&quot;, -&gt;
        ///    expect(true).toBeTruthy()
        ///    value = &quot;hello&quot;
        ///    expect(&quot;hello&quot;).toEqual value
        ///
        ///
        ///describe &quot;stringLib&quot;, -&gt;
        ///  it &quot;will get vowel count&quot;, -&gt;
        ///    count = stringLib.vowels(&quot;hello&quot;)
        ///    expect(count).toEqual 2
        ///
        ///
        ///describe &quot;mathLib&quot;, -&gt;
        ///  beforeEach -&gt;
        ///    console.log &quot;beforeEach&quot;
        ///
        ///  it &quot;will add 5 to number&quot;, -&gt;
        ///    res = mathLib.add5(10)
        ///    expect(res).toEqual 15
        ///
        ///  it &quot;will multiply 5 to number&quot;, -&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MochaSuiteCoffee {
            get {
                return ResourceManager.GetString("MochaSuiteCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;qunit.css&quot; type=&quot;text/css&quot;/&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;qunit-git.js&quot;&gt;&lt;/script&gt;
        ///
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;library.js&quot;&gt;&lt;/script&gt;
        ///
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;library-test.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        /// &lt;h1 id=&quot;qunit-header&quot;&gt;Unit Tests&lt;/h1&gt;
        /// &lt;h2 id=&quot;qunit-banner&quot;&gt;&lt;/h2&gt;
        /// &lt;h2 id=&quot;qunit-userAgent&quot;&gt;&lt;/h2&gt;
        /// &lt;ol id=&quot;qunit-tests&quot;&gt;&lt;/ol&gt;
        /// &lt;div id=&quot;qunit-fixture&quot;&gt;
        ///  &lt;ul&gt;
        ///    &lt;li&gt;Some&lt;/li&gt;
        ///    &lt;li&gt;Tes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QUnitHarness {
            get {
                return ResourceManager.GetString("QUnitHarness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&quot;qunit.js&quot; /&gt;
        ///// Example copief from http://docs.jquery.com/QUnit
        ///
        ///test(&quot;a basic test example&quot;, function () {
        ///    ok(true, &quot;this test is fine&quot;);
        ///    var value = &quot;hello&quot;;
        ///    equal(value, &quot;hello&quot;, &quot;We expect value to be hello&quot;);
        ///});
        ///
        ///module(&quot;Module A&quot;);
        ///
        ///test(&quot;first test within module&quot;, function () {
        ///    ok(true, &quot;all pass&quot;);
        ///});
        ///
        ///test(&quot;second test within module&quot;, function () {
        ///    ok(true, &quot;all pass&quot;);
        ///});
        ///
        ///module(&quot;Module B&quot;);
        ///
        ///test(&quot;some other test&quot;, function () {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QUnitSuite {
            get {
                return ResourceManager.GetString("QUnitSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## &lt;reference path=&quot;qunit.js&quot; /&gt;
        ///
        ///test &quot;A basic test&quot;, -&gt;
        ///  ok true, &quot;this test is fine&quot;
        ///  value = &quot;hello&quot;
        ///  equal &quot;hello&quot;, value, &quot;We expect value to be hello&quot;
        ///
        ///module &quot;stringLib&quot;
        ///test &quot;will get vowel count&quot;, -&gt;
        ///  count = stringLib.vowels(&quot;hello&quot;)
        ///  equal count, 2, &quot;We expect 2 vowels in hello&quot;
        ///
        ///module &quot;mathLib&quot;
        ///test &quot;will add 5 to number&quot;, -&gt;
        ///  res = mathLib.add5(10)
        ///  equal res, 15, &quot;should add 5&quot;
        ///
        ///test &quot;will multiply 5 to number&quot;, -&gt;
        ///  res = mathLib.mult5(10)
        ///  equal res, 55, &quot;should  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QUnitSuiteCoffee {
            get {
                return ResourceManager.GetString("QUnitSuiteCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&quot;yuitest.js&quot; /&gt;
        ///// Example copied from http://developer.yahoo.com/yui/examples/yuitest/yt-simple-example.html
        ///
        ///YAHOO.namespace(&quot;example.yuitest&quot;);
        ///
        ///YAHOO.example.yuitest.DataTestCase = new YAHOO.tool.TestCase({
        ///
        ///    //name of the test case - if not provided, one is auto-generated
        ///    name: &quot;Data Tests&quot;,
        ///
        ///    //---------------------------------------------------------------------
        ///    // setUp and tearDown methods - optional
        ///    //----------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YUITestSuite {
            get {
                return ResourceManager.GetString("YUITestSuite", resourceCulture);
            }
        }
    }
}
